### ISSUE TITLE
width and height should be used in example

### ISSUE THREAD

**Issue by dglaude** [pimoroni/scroll-phat-hd#15]
This would make them more portable, more robust, less magic number.
I can do a pull request for this, but first I want to know if it is OK an idea.

**Comment by Gadgetoid** [comment]
You're right. There are a couple of examples I can spot that use `17` in lieu of `scrollphathd.width`. The `width` and `height` properties on `scrollphathd` are read-only aliases of `_width` and `_height` which always reflect the physical screen dimensions, so they're safe to use in place of these magic numbers.
