### ISSUE TITLE
Zero sized fill should be OK and different from fill all.

### ISSUE THREAD

**Issue by dglaude** [pimoroni/scroll-phat-hd#18]
in is31fl3731.py :

fill should not use 0 as default value but a never used value like None that way a 0 width area is just no area at all.
This is what is used set_graph.

**Comment by Gadgetoid** [comment]
Looks like my use of zero could have some unintended consequences if, for example, the user called the `fill` function as part of, perhaps, a bar drawing routine which draws a zero to N height bar. IE: For convenience, they might sometimes want to fill a 0,N, N,0 or 0,0 area.

I'll tweak this in devel.
