### ISSUE TITLE
hashtagToScrollPhatHD to follow a user

### ISSUE THREAD

**Issue by luisbarreto** [pimoroni/scroll-phat-hd#30]
Hello,

This is not a real issue since the code is working to follow an hashtag; It's more an upgrade request.
Is it possible to make hashtagToScrollPhatHD to display Tweets from a specific user (knowing its ID or username)? i.e. instead of tracking **_hashtag_**, follow the tweets from a specific user (by username or ID).
Did some experiments but couldn't get it working.

**Comment by MrGJones** [comment]
Hi, I've not looked into that but it's surely possible and would be a great
addition to this cool script :)

**Comment by fhernand** [comment]
hi @luisbarreto, you can replace the "track" parameter with the "follow" parameter to filter for users. The parameter value is then the user id. Worked for me.

myStream.filter(follow=[userid], stall_warnings=True, async=True)

**Comment by MrGJones** [comment]
@fhernand i dont seem to have success with this?

**Comment by fhernand** [comment]
Are you using the twitter id? You can convert the user handle to get its corresponding id (e.g. here https://tweeterid.com/)

**Comment by MrGJones** [comment]
Aha! Thanks I'll give this a go.. 😀

**Comment by MrGJones** [comment]
@fhernand this seems to also include Replies to the userid

**Comment by fhernand** [comment]
@MrGJones correct, as documented here: https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters
you can apply some sort of filtering using these parameters (language, filter_level, replies) to tweak the set of tweets that are streamed

**Comment by MrGJones** [comment]
Yes I'll look into this and maybe add this feature as an option in the
script. Thank you 😊
