### ISSUE TITLE
Examples with fonts broken

### ISSUE THREAD

**Issue by LazyLizardJago** [pimoroni/scroll-phat-hd#33]
Hi,
I ran fine with all examples and my own code until running a dist-upgrade on my raspberry zero w yesterday. Now all examples (and my own code) don't show anything on the LEDs and run without any error or warning.
What kind of information do you need for debug? (And preferrably how do I get them :) )

**Comment by Gadgetoid** [comment]
You should post the output of:

```uname -a```

and

```lsb_release -a```

And see what pops up when you run `sudo i2c-detect -y 1`

**Comment by LazyLizardJago** [comment]
Hi,
the output of `uname -a`
Linux raspizero1 4.9.24+ #993 Wed Apr 26 17:56:54 BST 2017 armv6l GNU/Linux

`lsb_release -a`
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie

`sudo i2cdetect -y 1`
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- 74 -- -- --

**Comment by Gadgetoid** [comment]
If you're still seeing problems, I think the issue might be the brightness setting since a the version of Scroll pHAT HD includes Gamma Correction. I bet you've got older examples and a newer library.

Try setting the LED brightness in an example to something like 0.5.

**Comment by jose1711** [comment]
also maybe try this simple hw test using i2c-tools (should light a few pixels near the middle). tested on raspbian with pi zero w.
```
#!/bin/bash
addr="0x74"
ISET='i2cset -y 1'

echo "switch to configuration bank"
${ISET} $addr 0xfd 0x0b i

echo "switch to picture mode"
${ISET} $addr 0 0 i

echo "disable audio sync"
${ISET} $addr 0x06 0 i

echo "switch to bank 1"
${ISET} $addr 0xfd 1 i

${ISET} $addr 0xfd 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 i

echo "switch to bank 0"
${ISET} $addr 0xfd 0 i

echo "enable all leds"
${ISET} $addr 0xfd 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 i

echo "show some pixels"
${ISET} $addr 0x24 0x00 $(seq 1 31 | tr '\n' ' ') i
```

**Comment by LazyLizardJago** [comment]
@Gadgetoid The brightness solved the problem. The examples are working now again. The display flickers heavily but that might be something on my side.
