### ISSUE TITLE
Twitter example application not working...

### ISSUE THREAD

**Issue by mojeska** [pimoroni/scroll-phat-hd#35]
I believe I have configure the example tweet application correctly with apps.twitter.com keys, however nothing is displayed on the device when I post tweets with the hashtag added to the script.  All I ever see is an occasional four dots scroll across the screen.  Any help would be appreciated.

**Comment by mojeska** [comment]
The example tweet application imports a smoothed font, and that's apparently the problem.  Change the font to just the 5x7, and now things are working.

**Comment by morsh** [comment]
FYI, worked for me with:
`from scrollphathd.fonts import font5x7`
...
```
            scrollphathd.write_string(status,font=font5x7, brightness=0.1)
            status_length = scrollphathd.write_string(status, x=0, y=0,font=font5x7, brightness=0.1)
```
