### ISSUE TITLE
brightness value range in set_pixel? 0.0 to 1.0 or 0 to 255?

### ISSUE THREAD

**Issue by dglaude** [pimoroni/scroll-phat-hd#42]
The documentation of set_pixel linked here seems to say that brightness is Intensity of the pixel, from 0.0 to 1.0 or 0 to 255.

http://docs.pimoroni.com/scrollphathd/#set-a-single-pixel-in-buffer

But in practice is fail with the value 2:

ValueError: Value 2 out of range. Brightness should be between 0 and 1

Should the documentation be fixed and updated (and how) or the code?

**Comment by Gadgetoid** [comment]
Thanks for pointing this out, have updated the docstrings and republished the docs: http://docs.pimoroni.com/scrollphathd/#set-a-single-pixel-in-buffer
