### ISSUE TITLE
Dead Led row,  but only sometimes

### ISSUE THREAD

**Issue by Hyldig01** [pimoroni/scroll-phat-hd#52]
Hi, I have some problems with my scrollphatHd, when I start a script, all is good, but after a few minutes, a row of leds stop working

I have tried to use different scripts from the example folder,

The worst is switl.py... the dead row showed up at start, 

Any ideas what to do??

**Comment by Gadgetoid** [comment]
This could be an intermittent or dry solder joint that managed to sneak through testing. Which row is it? Could you snap a picture?

**Comment by Hyldig01** [comment]
its row 8 from from the right.  
Its a bit difficult to take a picture of it, but here's the best i could manage :D 
![img_0548](https://user-images.githubusercontent.com/33703671/37621897-9873ce68-2bc0-11e8-9fee-df92d5314c7a.JPG)

**Comment by Gadgetoid** [comment]
Thank you- yeah that's definitely wrong. You should ping our support team at support@pimoroni.com - link this issue and they should sort out a replacement.

**Comment by MrGJones** [comment]
Probably worth reflowing the solder joints on both the scrollphat and black
hat hack3r before hand just in case?
